# Usa un'immagine base Python ufficiale.
FROM python:3.10-slim-buster

# Imposta la directory di lavoro all'interno del container.
WORKDIR /app

# Imposta le variabili d'ambiente per disabilitare la verifica SSL (se ancora necessarie)
ENV PIP_NO_SSL_VERIFY=1
ENV PYTHONHTTPSVERIFY=0

# Installa le dipendenze di sistema necessarie, inclusi i tool per la compilazione e bash/nano.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    build-essential \
    bash \
    nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copia l'intero contenuto della directory corrente dell'host
COPY . .

# *** INIZIO MODIFICHE PER LA CARTELLA STORAGE ***

# Crea la cartella 'storage'
RUN mkdir -p /app/storage

# Imposta i permessi per la cartella 'storage'
# Questo è il metodo più robusto per OpenShift:
# - Cambia il gruppo proprietario a '0' (spesso il gruppo 'root', ma per OpenShift è il gruppo "anyuid")
# - Rende la cartella scrivibile dal gruppo (g+w)
# - Aggiunge il bit setgid (s) in modo che i nuovi file creati all'interno della cartella
#   appartengano automaticamente allo stesso gruppo (0). Questo è cruciale per OpenShift.
RUN chown -R 1001:0 /app/storage && chmod -R g+rwXs /app/storage

# *** FINE MODIFICHE PER LA CARTELLA STORAGE ***

# Installa le dipendenze Python
RUN pip install --no-cache-dir -r requirements.txt \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org

CMD ["python", "timerstamp.py"]